name: pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # الطباعة الحرارية عبر البلوتوث
  print_bluetooth_thermal: ^1.1.0

  # إدارة قواعد البيانات والملفات
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2

  # اختيار الملفات واسترجاع النسخ الاحتياطية
  file_picker: ^8.0.0

  # المكتبات المضافة للروابط والمشاركة
  url_launcher: ^6.2.5
  share_plus: ^8.0.3

  # جلب أسعار الصرف والتخزين المؤقت
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # مسار الموارد والصور
  assets:
    - assets/background.png
